# Module 3 Part 2: Operations with NumPy Arrays

This module consists of 2 parts:

- **Part 1** - NumPy Basics
- **Part 2** - Operations with NumPy Arrays

Each part is provided in a separate notebook file. It is recommended that you follow the order of the notebooks.

<h1>Table of Contents<span class="tocSkip"></span></h1>
<br>
<div class="toc">
<ul class="toc-item">
<li><span><a href="#Module-3-Part-2:-Operations-with-NumPy-Arrays" data-toc-modified-id="Module-3-Part-2:-Operations-with-NumPy-Arrays">Module 3 Part 2: Operations with NumPy Arrays</a></span>
</li>
<li><span><a href="#Table-of-Contents" data-toc-modified-id="Table-of-Contents">Table of Contents</a></span>
</li>
<li><span><a href="#Operations-with-NumPy-Arrays" data-toc-modified-id="Operations-with-NumPy-Arrays">Operations with NumPy Arrays</a></span>
<ul class="toc-item">
<li><span><a href="#Operations-between-arrays-and-scalars" data-toc-modified-id="Operations-between-arrays-and-scalars">Operations between arrays and scalars</a></span>
</li>
<li><span><a href="#Arithmetic-with-NumPy-arrays" data-toc-modified-id="Arithmetic-with-NumPy-arrays">Arithmetic with NumPy arrays</a></span>
<ul class="toc-item">
<li><span><a href="#Broadcasting" data-toc-modified-id="Broadcasting">Broadcasting</a></span>
</li>
<li><span><a href="#EXERCISE-3:-Array-mathematics" data-toc-modified-id="EXERCISE-3:-Array-mathematics">EXERCISE 3: Array mathematics</a></span>
</li>
</ul>
</li>
</ul>
</li>
<li><span><a href="#Basic-Indexing-and-Slicing" data-toc-modified-id="Basic-Indexing-and-Slicing">Basic Indexing and Slicing</a></span>
<ul class="toc-item">
<li><span><a href="#Indexing-with-slices" data-toc-modified-id="Indexing-with-slices">Indexing with slices</a></span>
</li>
<li><span><a href="#EXERCISE-4:-Indexing-and-Slicing" data-toc-modified-id="EXERCISE-4:-Indexing-and-Slicing">EXERCISE 4: Indexing and Slicing</a></span>
</li>
</ul>
</ul>
</div>

# Operations with NumPy Arrays

## Operations between arrays and scalars

You can perform arithmetic operations between arrays of any shape and scalars. In the result of this operation, the values are propagated to each element of the array.

For example, let's say we need to multiply all elements of an array by 5:

In [1]:
import numpy as np

# We will use an array of integers that we created in the previous section

arr_int = np.array([1, 2, 3, 4, 5])
arr_int

array([1, 2, 3, 4, 5])

In [2]:
# Multiply all elements of the array by 5

arr_int * 5

array([ 5, 10, 15, 20, 25])

In [3]:
# Raise all elements of the array, to the power of 2

1 / arr_int ** 2

array([1.        , 0.25      , 0.11111111, 0.0625    , 0.04      ])

## Arithmetic with NumPy arrays

Any arithmetic operations between equal-size arrays applies the operation element-wise:

In [4]:
array1 = np.array([[5, 4, 6, 1], [2, 3, 8, 10]])
array2 = np.array([[10, 12, 5, 17], [22, 33, 88, 100]])
print(array1)
print(array2)

[[ 5  4  6  1]
 [ 2  3  8 10]]
[[ 10  12   5  17]
 [ 22  33  88 100]]


In [5]:
array1 + array2

array([[ 15,  16,  11,  18],
       [ 24,  36,  96, 110]])

In [6]:
# Multiply arrays

array1 * array2

array([[  50,   48,   30,   17],
       [  44,   99,  704, 1000]])

In [7]:
# Subtract two arrays

array1 - array2

array([[ -5,  -8,   1, -16],
       [-20, -30, -80, -90]])

In [8]:
# Divide arrays

array1 / array2

array([[0.5       , 0.33333333, 1.2       , 0.05882353],
       [0.09090909, 0.09090909, 0.09090909, 0.1       ]])

In [9]:
# Calculate the remainder of two arrays

array1 % array2

array([[ 5,  4,  1,  1],
       [ 2,  3,  8, 10]])

As you can see, we can use `+`, `-`, `*`, `/` or `%` to add, subtract, multiply, divide or calculate the remainder of the arrays element-wise. 

We can achieve the same result by using NumPy functions: `np.add()`, `np.subtract()`, `np.multiply()`, `np.divide()` and `np.remainder()`.

In [10]:
np.add(array1,array2)

array([[ 15,  16,  11,  18],
       [ 24,  36,  96, 110]])

In [11]:
np.multiply(array1,array2)

array([[  50,   48,   30,   17],
       [  44,   99,  704, 1000]])

In [12]:
np.subtract(array1,array2)

array([[ -5,  -8,   1, -16],
       [-20, -30, -80, -90]])

In [13]:
np.divide(array1,array2)

array([[0.5       , 0.33333333, 1.2       , 0.05882353],
       [0.09090909, 0.09090909, 0.09090909, 0.1       ]])

In [14]:
np.remainder(array1,array2)

array([[ 5,  4,  1,  1],
       [ 2,  3,  8, 10]])

### Broadcasting

The term **broadcasting** refers to how NumPy treats arrays with different shapes during arithmetic operations. Frequently, we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array. For example, suppose that we want to add a constant vector to each row of a matrix. The smaller array is "broadcast" across the larger array so that they have compatible shapes.

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when:

- they are equal, or
- one of them is 1

The size of the resulting array is the maximum size along each dimension of the input arrays.

Arrays do not need to have the same number of dimensions. Dimensions with size 1 are stretched or "copied" to match the other dimensions. For example, below you can see that both input arrays, `A` and `B`, have axes with length one and expand to a larger size during the broadcast operation:


    A      (4-dimensional array):  8 x 1 x 6 x 1
    B      (3-dimensional array):      7 x 1 x 5
    Result (4-dimensional array):  8 x 7 x 6 x 5

More examples:

    A      (2-dim array):  5 x 4
    B      (1-dim array):      4
    Result (2-dim array):  5 x 4


    A      (3-dim array):  15 x 3 x 5
    B      (3-dim array):  15 x 1 x 5
    Result (3-dim array):  15 x 3 x 5


    A      (3-dim array):  15 x 3 x 5
    B      (2-dim array):       3 x 1
    Result (3-dim array):  15 x 3 x 5


Here is an example of broadcasting :

In [15]:
x1 = np.arange(4)        # create an array of integers from 0 to 3
x2 = x1.reshape(4,1)     # reshape() function allows us to change the shape of the array
                         # the resulting array will be a vector, 4 rows and 1 column
x2

array([[0],
       [1],
       [2],
       [3]])

In [16]:
y = np.ones(5)          # creating an array of 1s, 5-element array
y

array([1., 1., 1., 1., 1.])

In [17]:
x2.shape

(4, 1)

In [18]:
y.shape

(5,)

In [19]:
xy = x2 + y
xy

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [20]:
xy.shape

(4, 5)

In [21]:
# An array of 1s, 3 x 4

z = np.ones((3,4))
z

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
print(x1)
print(z)
print("---------------")
print(x1 + z)

[0 1 2 3]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
---------------
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


If arrays are of the same size, we can compare them. The result of the comparison is a boolean array:

In [26]:
array1 = np.array([[5, 4, 6, 1], [2, 3, 8, 10]])
array1

array([[ 5,  4,  6,  1],
       [ 2,  3,  8, 10]])

In [27]:
array2 = np.array([[0., 4., 1., 8.], [7., 2., 35, 12.]])
array2

array([[ 0.,  4.,  1.,  8.],
       [ 7.,  2., 35., 12.]])

In [28]:
array2 > array1

array([[False, False, False,  True],
       [ True, False,  True,  True]])

### EXERCISE 3: Array mathematics

1). Create 2 arrays:
  - Array `x`: array of 1s with dimensions 3 x 4,
  - Array `y`: array of random numbers with dimensions 5 x 1 x 4

In [32]:
# type your code here
x = np.ones((3,4))
print(x)

y = np.random.random((5,1,4))
print(y)




[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[0.26115944 0.71755118 0.15087886 0.62307735]]

 [[0.84416359 0.91484682 0.84325204 0.43051801]]

 [[0.11237519 0.47640432 0.97537667 0.34707011]]

 [[0.1999932  0.63904895 0.00807442 0.91479002]]

 [[0.74964039 0.49121661 0.41399013 0.58067367]]]


2). Add `x` and `y`

In [33]:
# type your code here
x + y



array([[[1.26115944, 1.71755118, 1.15087886, 1.62307735],
        [1.26115944, 1.71755118, 1.15087886, 1.62307735],
        [1.26115944, 1.71755118, 1.15087886, 1.62307735]],

       [[1.84416359, 1.91484682, 1.84325204, 1.43051801],
        [1.84416359, 1.91484682, 1.84325204, 1.43051801],
        [1.84416359, 1.91484682, 1.84325204, 1.43051801]],

       [[1.11237519, 1.47640432, 1.97537667, 1.34707011],
        [1.11237519, 1.47640432, 1.97537667, 1.34707011],
        [1.11237519, 1.47640432, 1.97537667, 1.34707011]],

       [[1.1999932 , 1.63904895, 1.00807442, 1.91479002],
        [1.1999932 , 1.63904895, 1.00807442, 1.91479002],
        [1.1999932 , 1.63904895, 1.00807442, 1.91479002]],

       [[1.74964039, 1.49121661, 1.41399013, 1.58067367],
        [1.74964039, 1.49121661, 1.41399013, 1.58067367],
        [1.74964039, 1.49121661, 1.41399013, 1.58067367]]])

3). Subtract `x` and `y`

In [34]:
# type your code here

x - y

array([[[0.73884056, 0.28244882, 0.84912114, 0.37692265],
        [0.73884056, 0.28244882, 0.84912114, 0.37692265],
        [0.73884056, 0.28244882, 0.84912114, 0.37692265]],

       [[0.15583641, 0.08515318, 0.15674796, 0.56948199],
        [0.15583641, 0.08515318, 0.15674796, 0.56948199],
        [0.15583641, 0.08515318, 0.15674796, 0.56948199]],

       [[0.88762481, 0.52359568, 0.02462333, 0.65292989],
        [0.88762481, 0.52359568, 0.02462333, 0.65292989],
        [0.88762481, 0.52359568, 0.02462333, 0.65292989]],

       [[0.8000068 , 0.36095105, 0.99192558, 0.08520998],
        [0.8000068 , 0.36095105, 0.99192558, 0.08520998],
        [0.8000068 , 0.36095105, 0.99192558, 0.08520998]],

       [[0.25035961, 0.50878339, 0.58600987, 0.41932633],
        [0.25035961, 0.50878339, 0.58600987, 0.41932633],
        [0.25035961, 0.50878339, 0.58600987, 0.41932633]]])

4). Multiply `x` and `y`

In [35]:
# type your code here

x * y

array([[[0.26115944, 0.71755118, 0.15087886, 0.62307735],
        [0.26115944, 0.71755118, 0.15087886, 0.62307735],
        [0.26115944, 0.71755118, 0.15087886, 0.62307735]],

       [[0.84416359, 0.91484682, 0.84325204, 0.43051801],
        [0.84416359, 0.91484682, 0.84325204, 0.43051801],
        [0.84416359, 0.91484682, 0.84325204, 0.43051801]],

       [[0.11237519, 0.47640432, 0.97537667, 0.34707011],
        [0.11237519, 0.47640432, 0.97537667, 0.34707011],
        [0.11237519, 0.47640432, 0.97537667, 0.34707011]],

       [[0.1999932 , 0.63904895, 0.00807442, 0.91479002],
        [0.1999932 , 0.63904895, 0.00807442, 0.91479002],
        [0.1999932 , 0.63904895, 0.00807442, 0.91479002]],

       [[0.74964039, 0.49121661, 0.41399013, 0.58067367],
        [0.74964039, 0.49121661, 0.41399013, 0.58067367],
        [0.74964039, 0.49121661, 0.41399013, 0.58067367]]])

5). Divide `x` and `y`

In [36]:
# type your code here

x / y

array([[[  3.82907846,   1.39362882,   6.62783396,   1.60493718],
        [  3.82907846,   1.39362882,   6.62783396,   1.60493718],
        [  3.82907846,   1.39362882,   6.62783396,   1.60493718]],

       [[  1.18460451,   1.09307917,   1.18588506,   2.32278318],
        [  1.18460451,   1.09307917,   1.18588506,   2.32278318],
        [  1.18460451,   1.09307917,   1.18588506,   2.32278318]],

       [[  8.89876122,   2.09905737,   1.02524495,   2.88126226],
        [  8.89876122,   2.09905737,   1.02524495,   2.88126226],
        [  8.89876122,   2.09905737,   1.02524495,   2.88126226]],

       [[  5.00017001,   1.56482535, 123.84791076,   1.09314704],
        [  5.00017001,   1.56482535, 123.84791076,   1.09314704],
        [  5.00017001,   1.56482535, 123.84791076,   1.09314704]],

       [[  1.33397294,   2.03576176,   2.41551655,   1.72213766],
        [  1.33397294,   2.03576176,   2.41551655,   1.72213766],
        [  1.33397294,   2.03576176,   2.41551655,   1.72213766]]])

In [37]:
# 1. Solution:

x = np.ones((3,4))
y = np.random.random((5,1,4))

In [38]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
y

array([[[0.94609999, 0.28792835, 0.74960016, 0.65523211]],

       [[0.02356738, 0.66946713, 0.0681755 , 0.01013378]],

       [[0.31713375, 0.67509978, 0.14517367, 0.23027928]],

       [[0.0467912 , 0.38604068, 0.27034872, 0.62409733]],

       [[0.68378607, 0.15567762, 0.44728159, 0.270846  ]]])

In [40]:
# 2. Solution
print(x + y)
# or 
print(np.add(x, y))

[[[1.94609999 1.28792835 1.74960016 1.65523211]
  [1.94609999 1.28792835 1.74960016 1.65523211]
  [1.94609999 1.28792835 1.74960016 1.65523211]]

 [[1.02356738 1.66946713 1.0681755  1.01013378]
  [1.02356738 1.66946713 1.0681755  1.01013378]
  [1.02356738 1.66946713 1.0681755  1.01013378]]

 [[1.31713375 1.67509978 1.14517367 1.23027928]
  [1.31713375 1.67509978 1.14517367 1.23027928]
  [1.31713375 1.67509978 1.14517367 1.23027928]]

 [[1.0467912  1.38604068 1.27034872 1.62409733]
  [1.0467912  1.38604068 1.27034872 1.62409733]
  [1.0467912  1.38604068 1.27034872 1.62409733]]

 [[1.68378607 1.15567762 1.44728159 1.270846  ]
  [1.68378607 1.15567762 1.44728159 1.270846  ]
  [1.68378607 1.15567762 1.44728159 1.270846  ]]]
[[[1.94609999 1.28792835 1.74960016 1.65523211]
  [1.94609999 1.28792835 1.74960016 1.65523211]
  [1.94609999 1.28792835 1.74960016 1.65523211]]

 [[1.02356738 1.66946713 1.0681755  1.01013378]
  [1.02356738 1.66946713 1.0681755  1.01013378]
  [1.02356738 1.66946713 1.0

In [41]:
# 3. Solution:
print(x - y)
# or 
print(np.subtract(x, y))

[[[0.05390001 0.71207165 0.25039984 0.34476789]
  [0.05390001 0.71207165 0.25039984 0.34476789]
  [0.05390001 0.71207165 0.25039984 0.34476789]]

 [[0.97643262 0.33053287 0.9318245  0.98986622]
  [0.97643262 0.33053287 0.9318245  0.98986622]
  [0.97643262 0.33053287 0.9318245  0.98986622]]

 [[0.68286625 0.32490022 0.85482633 0.76972072]
  [0.68286625 0.32490022 0.85482633 0.76972072]
  [0.68286625 0.32490022 0.85482633 0.76972072]]

 [[0.9532088  0.61395932 0.72965128 0.37590267]
  [0.9532088  0.61395932 0.72965128 0.37590267]
  [0.9532088  0.61395932 0.72965128 0.37590267]]

 [[0.31621393 0.84432238 0.55271841 0.729154  ]
  [0.31621393 0.84432238 0.55271841 0.729154  ]
  [0.31621393 0.84432238 0.55271841 0.729154  ]]]
[[[0.05390001 0.71207165 0.25039984 0.34476789]
  [0.05390001 0.71207165 0.25039984 0.34476789]
  [0.05390001 0.71207165 0.25039984 0.34476789]]

 [[0.97643262 0.33053287 0.9318245  0.98986622]
  [0.97643262 0.33053287 0.9318245  0.98986622]
  [0.97643262 0.33053287 0.9

In [42]:
# 4. Solution:
print(x * y)
# or 
print(np.multiply(x, y))

[[[0.94609999 0.28792835 0.74960016 0.65523211]
  [0.94609999 0.28792835 0.74960016 0.65523211]
  [0.94609999 0.28792835 0.74960016 0.65523211]]

 [[0.02356738 0.66946713 0.0681755  0.01013378]
  [0.02356738 0.66946713 0.0681755  0.01013378]
  [0.02356738 0.66946713 0.0681755  0.01013378]]

 [[0.31713375 0.67509978 0.14517367 0.23027928]
  [0.31713375 0.67509978 0.14517367 0.23027928]
  [0.31713375 0.67509978 0.14517367 0.23027928]]

 [[0.0467912  0.38604068 0.27034872 0.62409733]
  [0.0467912  0.38604068 0.27034872 0.62409733]
  [0.0467912  0.38604068 0.27034872 0.62409733]]

 [[0.68378607 0.15567762 0.44728159 0.270846  ]
  [0.68378607 0.15567762 0.44728159 0.270846  ]
  [0.68378607 0.15567762 0.44728159 0.270846  ]]]
[[[0.94609999 0.28792835 0.74960016 0.65523211]
  [0.94609999 0.28792835 0.74960016 0.65523211]
  [0.94609999 0.28792835 0.74960016 0.65523211]]

 [[0.02356738 0.66946713 0.0681755  0.01013378]
  [0.02356738 0.66946713 0.0681755  0.01013378]
  [0.02356738 0.66946713 0.0

In [43]:
# 5. Solution
print(x / y)
# or
print(np.divide(x, y))

[[[ 1.05697073  3.47308629  1.33404453  1.52617672]
  [ 1.05697073  3.47308629  1.33404453  1.52617672]
  [ 1.05697073  3.47308629  1.33404453  1.52617672]]

 [[42.43153801  1.49372531 14.66802573 98.67990678]
  [42.43153801  1.49372531 14.66802573 98.67990678]
  [42.43153801  1.49372531 14.66802573 98.67990678]]

 [[ 3.15324367  1.48126251  6.8883014   4.34255309]
  [ 3.15324367  1.48126251  6.8883014   4.34255309]
  [ 3.15324367  1.48126251  6.8883014   4.34255309]]

 [[21.3715393   2.59040058  3.69892635  1.60231417]
  [21.3715393   2.59040058  3.69892635  1.60231417]
  [21.3715393   2.59040058  3.69892635  1.60231417]]

 [[ 1.4624457   6.42353108  2.23572805  3.69213508]
  [ 1.4624457   6.42353108  2.23572805  3.69213508]
  [ 1.4624457   6.42353108  2.23572805  3.69213508]]]
[[[ 1.05697073  3.47308629  1.33404453  1.52617672]
  [ 1.05697073  3.47308629  1.33404453  1.52617672]
  [ 1.05697073  3.47308629  1.33404453  1.52617672]]

 [[42.43153801  1.49372531 14.66802573 98.67990678]


# Basic Indexing and Slicing

One-dimensional arrays can be indexed, sliced and iterated over to select a subset of elements of NumPy arrays, similar to lists and other Python sequences. NumPy arrays are indexed like a list, so the index starts with zero.

In [46]:
a = np.arange(2,10)
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a[3]     # this index points to the 4th element of the array

5

In [48]:
a[1:5]    # elements with indexes 1 to 4, the end index is exclusive

array([3, 4, 5, 6])

A slicing operation creates a **view** on the original array, the data from the original array is not copied in memory. This also means that any changes to the elements of the slice (view) are done to the oiginal array. Let's illustrate:

In [49]:
a_view = a[1:5]
a_view[2] = 12      # change the value of the 3rd element of a view to 12
a_view

array([ 3,  4, 12,  6])

The 3rd element of a view `a_view` is the 4th element of an array `a`:

In [50]:
a

array([ 2,  3,  4, 12,  6,  7,  8,  9])

As you can see, the value of the 4th element of the original array `a` changed to `12` as well. 

We might need to change all elements of a view. For this operation, we will use slice, `[:]`.

In [51]:
a_view[:] = 345
a

array([  2, 345, 345, 345, 345,   7,   8,   9])

For **multidimensional** arrays,  indexes are tuples of integers.

For example, to select an index of a two-dimensional array:

In [52]:
a_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
# Indexing:

a_2d[2]

array([7, 8, 9])

To select an individual element of a 2-dimensional array, we need to use a list of indices. In 2-dimensional arrays, the first dimension corresponds to rows, the second to columns:

In [54]:
a_2d[0,1]

2

Indexing **multidimensional** arrays:

In [56]:
# Creating 2x2x3 array:
# 2 planes x 2 rows x 3 colums

a_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
a_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

If we simply provide one index, `a_3d[0]`, the result will be a lower-dimensional `ndarray` of all the data along the higher dimensions, which is a `2 × 3` array:

In [57]:
a_3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

If 2 indices are specified `a_3d[1, 1]`, the result is a 1-dimensional array of all values where indices start with (1, 1):

In [58]:
a_3d[1, 1]

array([10, 11, 12])

## Indexing with slices

Slicing 2-dimensional arrays is slightly different than slicing 1-dimensional arrays. In a 2-dimensional array, a slice selects elements along the axis.

In [59]:
# Using 2-dimensional array from the previous section

a_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

The following line will select the first 2 rows &mdash; the rows with indices 0 and 1 &mdash; along axis = 0 (rows):

In [60]:
a_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

To pass multiple slices:

In [61]:
a_2d[:1, 1:]

array([[2, 3]])

If integer indexes and slices are mixed, the lower dimensional slices are selected. In the next example, we are selecting the 3rd row and only 1st column which in this particular example will return only 1 element:

In [62]:
a_2d[2, :1]

array([7])

`[:]` selects an entire axis:

In [63]:
a_2d[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

## EXERCISE 4: Indexing and Slicing

1). Create a 2-dimensional 5x10 array of integers from 1 to 50 (inclusive).

**HINT:** You can create a one-dimensional array usingthe  `arange()` function and change the shape of the array using the `reshape()` function introduced in the **Broadcasting** section above.

In [67]:
# Type your code here:

array5by10 = None
array5by10 = np.arange(1, 51).reshape(5,10)
#print(array5by10)
array5by10

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

2). Select the second row of the array.

In [68]:
array5by10[1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

3). Select the second element from each row of the array. The result will be a one-dimensional array of 5 elements.

In [69]:
array5by10[:,1]

array([ 2, 12, 22, 32, 42])

4). Select numbers 16, 17 and 18 from the array.

In [70]:
array5by10[1,5:8]

array([16, 17, 18])

5). Update the fifth element in the third row of the array by replacing number 25 with 255.

In [74]:
array5by10[2,4] = 255

In [75]:
# Solution:
# 1). Creating an array

array5by10 = np.arange(1, 51).reshape(5,10)
array5by10

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [76]:
# 2). Second row of the array

array5by10[1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [77]:
# 3). Second element from each row of the array will output a one-dimensional array

array5by10[:,1]

array([ 2, 12, 22, 32, 42])

In [78]:
# 4). Selecting numbers 16, 17 and 18 from the array
# These numbers are in the second row (index = 1), their indices within the row are 5, 6 and 7 correspondingly
# but we need to remember that the last index in the slice is not included

array5by10[1,5:8]

array([16, 17, 18])

In [79]:
# 5). First, let's make sure we have the right index for number 25

array5by10[2,4]

25

In [80]:
# Updating the element

array5by10[2,4] = 255
array5by10

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24, 255,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50]])

**End of Module**


You have reached the end of this module. 

If you have any questions, please reach out to your peers using the discussion boards. If you and your peers are unable to come to a suitable conclusion, do not hesitate to reach out to your instructor on the designated discussion board.

When you are comfortable with the content, and have practiced to your satisfaction, you may proceed to any related assignments, and to the next module.